### PR TITLE
Made a sub-folder to keep both Japanese and English as separate documents

### PR DESCRIPTION
**Pull request by shinobukawano**
@dongryphon san

I'm trying to separate the documents. What do you think about this?

### CODE REVIEW

**Comment by dongryphon** [comment]
I combined your "ja" folder with the original to keep some words on the landing page. I also added an icon link bar to the top. Thoughts?

**Comment by dongryphon** [comment]
Since the merge was manual, you'd need a new branch based on `master` to continue.

**Comment by dongryphon** [comment]
Thanks for all the hard work on this by the way! Awesome stuff!

**Comment by shinobukawano** [comment]
That's perfect!! I really like your idea! We can easily find the translation, but it does not disturb the main contents.. awesome. :+1: 
Thank you so much!!

**Pull request closed without merging**
